language: java
branches:
  only:
    - route-manager-release
jdk:
  - oraclejdk8

sudo: required

services:
  - docker

install:
  - cd "delegate" && mvn clean install -DskipTests=true
  - docker build -t tilaks/router .
  - docker ps -a
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push tilaks/router

script: mvn clean install -DskipTests=true

after-success:
  - cd /home/ec2-user/router-microservice

before_deploy:
  - pwd
  - cd /home/travis/build/airavata-courses/TeamAviato/
  - zip -r SGA_Aviato_RouteManager.zip delegate scripts appspec.yml || true
  - mkdir -p "dpl_cd_upload"
  - mv SGA_Aviato_RouteManager.zip dpl_cd_upload/SGA_Aviato_RouteManager.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: teamaviatobucket-ohio
    local_dir: dpl_cd_upload
    region: us-east-2
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      branch: route-manager-release
      
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: teamaviatobucket-ohio
    key: SGA_Aviato_RouteManager.zip
    bundle_type: zip
    application: TeamAviatoApp-ohio
    deployment_group: TeamAviatoApp-ohio
    region: us-east-2
    skip_cleanup: true
    on:
      branch: route-manager-release

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: teamaviatobucket-ohio
    local_dir: dpl_cd_upload
    region: us-east-2
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      branch: route-manager-release
      
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: teamaviatobucket-ohio
    key: SGA_Aviato_RouteManager.zip
    bundle_type: zip
    application: TeamAviatoApp-ohio2
    deployment_group: TeamAviatoApp-ohio2
    region: us-east-2
    skip_cleanup: true
    on:
      branch: route-manager-release
      
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: teamaviatobucket2
    local_dir: dpl_cd_upload
    region: us-west-2
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      branch: route-manager-release

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: teamaviatobucket2
    key: SGA_Aviato_RouteManager.zip
    bundle_type: zip
    application: TeamAviatoApp
    deployment_group: TeamAviatoApp
    region: us-west-2
    skip_cleanup: true
    on:
      branch: route-manager-release
